.\" Manpage for scaledcars-example
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH scaledcars-example 1 "27 March 2017" "0.0.6" "scaledcars-example man page"

.SH NAME
scaledcars-example \- Example software for scaled cars.



.SH SYNOPSIS
.B scaledcars-example --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B scaledcars-example --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

